name: Node.js Packages version bump
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Set commit author email
        run: git config --global user.email "development@itgalaxy.company"
      - name: Set commit author name
        run: git config --global user.name "itgalaxy"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Pull all tags from Lerna semantic release
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project dependencies
        run: npm ci --no-optional
      - name: Bump versions and create release
        run: npm run release
      - name: Push tags
        run: npm run push-tags
      - name: Push commits
        run: git push origin
